apiVersion: kaptain.org/1.19
kind: kubernetes-bundle-resources
metadata:
  description: "Keelson controller - bash scripts and Kubernetes manifest templates, bundled as a tagged release artefact for downstream helm-chart and runtime-image repos"

spec:
  layers:
    - ghcr.io/kube-kaptain/layer/layer-github-flow-strict:[1.3,2)
  main:
    hooks:
      preTaggingTests: .github/bin/run-tests.bash
      prePackagePrepare: .github/bin/package-scripts.bash
  global:
    release:
      versioning:
        maxParts: '2'
  platform:
    githubActions:
      release:
        verbatimFiles: kaptain-out/keelson-scripts.zip
