apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${ProjectName}-clusterrolebinding-checksum
subjects:
  - kind: ServiceAccount
    name: ${ProjectName}
    namespace: ${Environment}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${ProjectName}-clusterrole-checksum
