apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${ProjectName}
  namespace: ${Environment}
  labels:
    kaptain.org/environment: ${Environment}
    kaptain.org/product: ${ProductName}
    kaptain.org/project-name: ${ProjectName}
    kaptain.org/version: "${Version}"
    kaptain.org/owner: ${RepositoryOwner}
    app.kubernetes.io/name: ${ProjectName}
    app.kubernetes.io/instance: ${ProjectName}
    app.kubernetes.io/version: "${Version}"
    app.kubernetes.io/managed-by: Kaptain
    app: ${ProjectName}
    app.kubernetes.io/part-of: ${ProductName}
  annotations:
    kaptain.org/source-repository: ${RepositoryOwner}/${RepositoryName}
